/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Conversation = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'messages' : IDL.Text,
  'mode' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Mode = IDL.Variant({
  'pro' : IDL.Null,
  'fast' : IDL.Null,
  'thinking' : IDL.Null,
  'ultra' : IDL.Null,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'createAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteConversation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'getConversations' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Conversation)],
      ['query'],
    ),
  'loginAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Conversation)], []),
  'saveConversation' : IDL.Func(
      [IDL.Text, IDL.Text, Conversation],
      [IDL.Bool],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)), IDL.Text, Mode],
      [IDL.Text],
      [],
    ),
  'transform' : IDL.Func([TransformInput], [TransformOutput], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Conversation = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'messages' : IDL.Text,
    'mode' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Mode = IDL.Variant({
    'pro' : IDL.Null,
    'fast' : IDL.Null,
    'thinking' : IDL.Null,
    'ultra' : IDL.Null,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'createAccount' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteConversation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'getConversations' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Conversation)],
        ['query'],
      ),
    'loginAccount' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Conversation)],
        [],
      ),
    'saveConversation' : IDL.Func(
        [IDL.Text, IDL.Text, Conversation],
        [IDL.Bool],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)), IDL.Text, Mode],
        [IDL.Text],
        [],
      ),
    'transform' : IDL.Func([TransformInput], [TransformOutput], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };